server.port=8081

# Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
# Dán chuỗi mã hóa thu được ở Bước 2 vào sau {cipher}
spring.datasource.password=83f3e493950dc4c50f261936cb8bf99a3764a9897db5e720c5a12d2efc2d5e32
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator & Dynamic Refresh
management.endpoints.web.exposure.include=refresh
app.welcome=Chào mừng tới BV RikkeiAcademy
